name: App CI

on:
  push:

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "SkyeRangerDelta/PlDyn-Webapp"

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-version: [ 20.x, 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache NodeJS Modules
        uses: actions/cache@v4
        with:
          path: webapp/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('webapp/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Generate ENV
        run: |
          pwd
          touch .env
          echo $ENV_DATA | base64 --decode > .env

      - name: Test
        run: |
          cd webapp
          npm ci
          npm run test:ci

      - name: Build
        run: |
          cd webapp
          npm run build:ci
